# Naive Bayes 실습

# 1. Gaussian Naive Bayes

- 데이터, 모듈 불러오기

# MarkDown
## MarkDown
### MarkDown
MarkDown
**python** is really good
-python
 - pandas
 - numpy
-  java

In [5]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

In [6]:
import pandas as pd

In [7]:
iris = datasets.load_iris()
df_X=pd.DataFrame(iris.data)
df_Y=pd.DataFrame(iris.target)

In [8]:
df_X.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [9]:
df_Y.head()

0
0  0
1  0
2  0
3  0
4  0

- 모델 피팅

In [10]:
gnb=GaussianNB()
fitted=gnb.fit(iris.data, iris.target)
y_pred = fitted.predict(iris.data)

In [11]:
fitted.predict_proba(iris.data)[[1, 48, 51, 100]]

array([[1.00000000e+000, 1.51480769e-017, 2.34820051e-025],
       [1.00000000e+000, 2.63876217e-018, 2.79566024e-025],
       [7.27347795e-102, 9.45169639e-001, 5.48303606e-002],
       [3.23245181e-254, 6.35381031e-011, 1.00000000e+000]])

In [12]:
fitted.predict(iris.data)[[1, 48, 51, 100]]

array([0, 0, 1, 2])

- Confusion matrix 구하기

In [13]:
from sklearn.metrics import confusion_matrix

In [14]:
confusion_matrix(iris.target,y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  3, 47]], dtype=int64)

- Prior 설정하기

In [16]:
gnb2 = GaussianNB(priors = [1/100, 1/100, 98/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_pred2 = fitted2.predict(iris.data)
confusion_matrix(iris.target, y_pred2)

array([[50,  0,  0],
       [ 0, 33, 17],
       [ 0,  0, 50]], dtype=int64)

In [17]:
gnb2 = GaussianNB(priors = [1/100, 98/100, 1/100])
fitted2 = gnb2.fit(iris.data, iris.target)
y_pred2 = fitted2.predict(iris.data)
confusion_matrix(iris.target, y_pred2)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0, 14, 36]], dtype=int64)

# 2. Multinomial naive bayes

- 모듈 불러오기 및 데이터 생성

In [18]:
from sklearn.naive_bayes import MultinomialNB

In [19]:
import numpy as np

In [20]:
X = np.random.randint(5, size=(6, 100))
y = np.array([1, 2, 3, 4, 5, 6])

In [21]:
X

array([[2, 4, 4, 4, 1, 2, 3, 2, 3, 0, 1, 0, 0, 2, 0, 4, 1, 2, 4, 0, 2, 1,
        3, 2, 0, 0, 1, 1, 0, 4, 0, 4, 1, 4, 0, 4, 1, 1, 3, 0, 3, 4, 3, 0,
        3, 3, 4, 4, 0, 1, 4, 2, 3, 2, 1, 1, 4, 4, 0, 4, 1, 0, 2, 0, 3, 3,
        1, 2, 4, 4, 3, 3, 2, 4, 3, 3, 4, 2, 0, 4, 2, 4, 1, 0, 0, 1, 1, 3,
        2, 1, 1, 1, 4, 2, 3, 2, 0, 1, 1, 0],
       [3, 4, 0, 0, 4, 4, 0, 4, 1, 1, 1, 3, 4, 4, 4, 0, 3, 2, 4, 0, 3, 3,
        1, 1, 2, 3, 3, 0, 4, 2, 0, 3, 4, 4, 3, 4, 0, 3, 3, 0, 4, 0, 0, 0,
        4, 2, 4, 4, 3, 3, 0, 3, 3, 4, 0, 4, 4, 3, 3, 4, 1, 4, 2, 2, 3, 4,
        1, 3, 2, 0, 2, 2, 3, 4, 4, 2, 4, 2, 1, 1, 2, 0, 3, 4, 0, 2, 2, 3,
        4, 1, 1, 2, 4, 1, 4, 0, 3, 3, 1, 0],
       [2, 2, 4, 2, 3, 1, 1, 4, 2, 0, 1, 2, 3, 4, 4, 1, 4, 4, 4, 3, 4, 4,
        2, 0, 0, 0, 2, 1, 0, 3, 4, 2, 0, 4, 0, 2, 4, 2, 0, 3, 2, 0, 1, 3,
        1, 4, 4, 2, 3, 2, 1, 0, 3, 4, 1, 0, 3, 1, 0, 4, 2, 2, 0, 0, 2, 0,
        4, 2, 2, 4, 3, 4, 2, 1, 1, 3, 3, 3, 1, 4, 4, 2, 4, 1, 4, 1, 2, 1,
        1, 0, 0, 0, 0,

In [22]:
y

array([1, 2, 3, 4, 5, 6])

- Multinomial naive bayes 모델 생성

In [23]:
clf = MultinomialNB()
clf.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [24]:
print(clf.predict(X[2:3]))

[3]


In [26]:
clf.predict_proba(X[2:3])

array([[1.64209245e-32, 1.44363745e-36, 1.00000000e+00, 1.46271040e-43,
        3.15027465e-31, 4.73839786e-44]])

- prior 변경해보기

In [29]:
clf2 = MultinomialNB(class_prior=[0.1, 0.1999, 0.0001, 0.1, 0.1, 0.1])
clf2.fit(X, y)

MultinomialNB(alpha=1.0, class_prior=[0.1, 0.1999, 0.0001, 0.1, 0.1, 0.1],
              fit_prior=True)

In [31]:
clf2.predict_proba(X[2:3])

array([[1.64209245e-29, 2.88583126e-33, 1.00000000e+00, 1.46271040e-40,
        3.15027465e-28, 4.73839786e-41]])

In [32]:
temp = 25.5
prob = 80.0
a = '오늘 기온 {}, 비올 확률{}'.format(temp, prob)
print(a)

오늘 기온 25.5, 비올 확률80.0


In [33]:
c = (1, 2, 3)
d = list(c)
print(d)

[1, 2, 3]


In [36]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(a[:])
print(a[1:])
print(a[0:9:2])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 3, 5, 7, 9]


In [37]:
a = {'a' : 1, 'b' : 2, 'c'  : 3}
b = {'a' : 2, 'd' : 4, 'e' : 5, 'f' : 6}
a.update(b)
print(a)

{'a': 2, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


In [38]:
del a['b']
print(a)

{'a': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6}


In [39]:
c = 'b' in a
print(c)

False


In [40]:
print(a.get('d'))

4


In [41]:
c = list(a.keys())

In [42]:
print(c)

['a', 'c', 'd', 'e', 'f']


In [43]:
d = list(a.values())

In [44]:
print(d)

[2, 3, 4, 5, 6]


In [45]:
a = [1, 10, 20, 100]
for value in a:
    print(value, value*2)

1 2
10 20
20 40
100 200


In [46]:
a = [10, 20, 30, 40]
for index, value in enumerate(a):
    print(index, value)

0 10
1 20
2 30
3 40


In [52]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
for i in a[1:]:
    for j in a:
        print(i, "*", j, "=", i*j)

2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81


In [54]:
a = list(range(10))
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [56]:
b = list(range(10, 20))
print(b)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [57]:
c = list(range(10, 20, 2))
print(c)

[10, 12, 14, 16, 18]


In [59]:
#while문으로 구구단
i = 2
while (i <= 9):
    j=1
    while (j <= 9):
        print("{}x{}={}".format(i, j, i*j))
        j+=1
    i+=1

2x1=2
2x2=4
2x3=6
2x4=8
2x5=10
2x6=12
2x7=14
2x8=16
2x9=18
3x1=3
3x2=6
3x3=9
3x4=12
3x5=15
3x6=18
3x7=21
3x8=24
3x9=27
4x1=4
4x2=8
4x3=12
4x4=16
4x5=20
4x6=24
4x7=28
4x8=32
4x9=36
5x1=5
5x2=10
5x3=15
5x4=20
5x5=25
5x6=30
5x7=35
5x8=40
5x9=45
6x1=6
6x2=12
6x3=18
6x4=24
6x5=30
6x6=36
6x7=42
6x8=48
6x9=54
7x1=7
7x2=14
7x3=21
7x4=28
7x5=35
7x6=42
7x7=49
7x8=56
7x9=63
8x1=8
8x2=16
8x3=24
8x4=32
8x5=40
8x6=48
8x7=56
8x8=64
8x9=72
9x1=9
9x2=18
9x3=27
9x4=36
9x5=45
9x6=54
9x7=63
9x8=72
9x9=81


In [63]:
#1-100까지 정수 중 2의 배수 또는 11의 배수 출력
a = range(1, 101)
for i in a:
    if (a[i] % 2 == 0) or (a[i] %11 == 0) :
        print(a[i])
        

2
4
6
8
10
11
12
14
16
18
20
22
24
26
28
30
32
33
34
36
38
40
42
44
46
48
50
52
54
55
56
58
60
62
64
66
68
70
72
74
76
77
78
80
82
84
86
88
90
92
94
96
98
99
100


IndexError: range object index out of range