### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [7]:
np.random.rand(4, 5, 3)

array([[[0.68537208, 0.90077887, 0.83523144],
        [0.02973025, 0.19237635, 0.8044267 ],
        [0.53318641, 0.13351709, 0.14553189],
        [0.96036275, 0.18440558, 0.86308692],
        [0.53193762, 0.5161577 , 0.35538892]],

       [[0.36801125, 0.36174209, 0.6059647 ],
        [0.17851284, 0.07543905, 0.42734888],
        [0.85615561, 0.02598177, 0.2064015 ],
        [0.33273994, 0.47408756, 0.40610472],
        [0.74801794, 0.73943216, 0.99557685]],

       [[0.38601723, 0.22288065, 0.09542868],
        [0.25132318, 0.56690012, 0.94659225],
        [0.9152552 , 0.65483615, 0.38914586],
        [0.10707276, 0.41035571, 0.02104336],
        [0.34240564, 0.11759002, 0.2140861 ]],

       [[0.15109985, 0.75055504, 0.51521585],
        [0.95999935, 0.01330679, 0.43117973],
        [0.96843902, 0.65052464, 0.83926949],
        [0.11452605, 0.30525423, 0.15004178],
        [0.15778355, 0.97389989, 0.31318482]]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [9]:
np.random.randn(3, 4, 2)

array([[[ 1.29701876, -0.56257362],
        [ 2.4583449 ,  0.02022395],
        [ 2.06681065,  0.17679377],
        [ 0.78193939, -0.50689108]],

       [[ 1.55046881,  0.2161295 ],
        [-0.21469806, -0.99540906],
        [ 0.10720286,  0.18518082],
        [ 0.28612183, -1.04592511]],

       [[-2.30317309, -0.17283694],
        [-1.27112809,  0.22402832],
        [ 0.55346996, -0.66185739],
        [ 0.84448126, -0.172756  ]]])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [11]:
np.random.randint(1, 100, size=(3, 5, 2))

array([[[87, 95],
        [70, 64],
        [91, 91],
        [70, 84],
        [37, 81]],

       [[35, 88],
        [15, 74],
        [60,  5],
        [ 4, 19],
        [ 8, 88]],

       [[52, 19],
        [80, 51],
        [36, 19],
        [44, 75],
        [37, 44]]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [24]:
np.random.seed(100)

In [25]:
np.random.randn(3, 4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [26]:
np.random.choice(100, (3, 4))

array([[83,  4, 91, 59],
       [67,  7, 49, 47],
       [65, 61, 14, 55]])

In [30]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])
np.random.choice(x, size=(2, 2), replace=False)

array([[1. , 2.6],
       [4.9, 3. ]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [31]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.20760908, 1.21029537, 1.76388689, 1.07295211, 2.78082313],
       [2.96184171, 1.11988398, 2.78109189, 2.153803  , 2.48495938],
       [2.26036787, 2.16368438, 1.04087826, 1.42005316, 2.08936976],
       [2.53823034, 1.50139046, 1.57179138, 2.70479018, 2.95001299]])

In [32]:
np.random.normal(size = (3, 4)) # 정규분포

array([[-0.30609783,  0.83850061, -1.69084816,  1.15117366],
       [-1.02933685, -0.51099219, -2.36027053,  0.10359513],
       [ 1.73881773,  1.24187584,  0.13241276,  0.57779396]])