## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [1]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

#### 연산 함수
 - add, substract, multiply, divide

In [9]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.03909825 0.55576363 0.90100331 0.13256848 0.67688537]
 [0.22924609 0.94897203 0.30466985 0.48622834 0.78411215]
 [0.03609651 0.91401228 0.30152706 0.90138042 0.55335182]]


In [10]:
np.add(x, y)

array([[ 0.03909825,  1.55576363,  2.90100331,  3.13256848,  4.67688537],
       [ 5.22924609,  6.94897203,  7.30466985,  8.48622834,  9.78411215],
       [10.03609651, 11.91401228, 12.30152706, 13.90138042, 14.55335182]])

In [11]:
# # shape이 다른 경우?
# x = np.arange(15).reshape(3, 5)
# y = np.random.rand(16).reshape(4, 4)
# print(x)
# print(y)
# np.add(x, y) # 오류 발생. shape이 같아야 한다

In [13]:
x + y

array([[ 0.03909825,  1.55576363,  2.90100331,  3.13256848,  4.67688537],
       [ 5.22924609,  6.94897203,  7.30466985,  8.48622834,  9.78411215],
       [10.03609651, 11.91401228, 12.30152706, 13.90138042, 14.55335182]])

In [14]:
x - y

array([[-0.03909825,  0.44423637,  1.09899669,  2.86743152,  3.32311463],
       [ 4.77075391,  5.05102797,  6.69533015,  7.51377166,  8.21588785],
       [ 9.96390349, 10.08598772, 11.69847294, 12.09861958, 13.44664818]])

In [15]:
x / y

array([[  0.        ,   1.79932611,   2.21974767,  22.62981416,
          5.90942009],
       [ 21.81062234,   6.32263104,  22.97569028,  16.45317522,
         11.4779499 ],
       [277.03505526,  12.03484918,  39.79742343,  14.42232356,
         25.30035948]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [16]:
print(y)

[[0.03909825 0.55576363 0.90100331 0.13256848 0.67688537]
 [0.22924609 0.94897203 0.30466985 0.48622834 0.78411215]
 [0.03609651 0.91401228 0.30152706 0.90138042 0.55335182]]


In [17]:
np.mean(y)

0.5176610385401572

In [18]:
y.mean()

0.5176610385401572

In [19]:
np.max(y)

0.9489720278644614

In [22]:
np.argmax(y) # flatten한 상태를 가정하고 index를 가져온다

6

In [24]:
np.var(y), np.median(y), np.std(y)

(0.10145752779327898, 0.5533518214245857, 0.31852398307392643)

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [26]:
np.sum(y)

7.764915578102358

In [27]:
np.cumsum(y)

array([0.03909825, 0.59486187, 1.49586518, 1.62843366, 2.30531903,
       2.53456512, 3.48353715, 3.788207  , 4.27443533, 5.05854748,
       5.094644  , 6.00865628, 6.31018334, 7.21156376, 7.76491558])

In [30]:
np.sum(y, axis=1) # 축을 따라서 더한다

array([2.30531903, 2.75322846, 2.70636809])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [32]:
z = np.random.randn(10)
print(z)

[-1.05176603 -0.0691948  -1.9524877   0.39419483  2.9200675   0.05419982
  0.32687493  0.71438996  1.08054148  0.6802127 ]


In [34]:
z > 0

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [33]:
np.any(z > 0)

True

In [36]:
np.all(z > 0) # 모두 참이어야지만 True

False

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [37]:
z = np.random.randn(10)
print(z)

[-1.00385261 -0.65239422  0.10932214  1.06733784 -0.987055   -0.83547207
 -0.45671135  1.00526221 -2.54150878  0.44451284]


In [40]:
np.where(z > 0, z, 0)

array([0.        , 0.        , 0.10932214, 1.06733784, 0.        ,
       0.        , 0.        , 1.00526221, 0.        , 0.44451284])