## 학습목표
 1. linalg 서브모듈 함수 활용여 선형대수 연산하기

In [7]:
import numpy as np

#### np.linalg.inv
 - 역행렬을 구할 때 사용
 - 모든 차원의 값이 같아야 함

In [10]:
x = np.random.rand(3, 3)
print(x)

x @ np.linalg.inv(x)

[[0.23542589 0.46245948 0.41954669]
 [0.33373462 0.55644215 0.96401705]
 [0.42035288 0.94072003 0.53716435]]


array([[ 1.00000000e+00,  8.88178420e-16, -8.88178420e-16],
       [-8.88178420e-15,  1.00000000e+00,  0.00000000e+00],
       [-3.55271368e-15,  4.44089210e-16,  1.00000000e+00]])

#### np.linalg.solve
 - Ax = B 형태의 선형대수식 솔루션을 제공
 - 예제) 호랑이와 홍합의 합 : 25 호랑이 다리와 홍합 다리의 합은 64
   - x + y = 25
   - 2x + 4y = 64
   
 $$\begin{pmatrix} 1 & 1 \\ 2 & 4 \end{pmatrix}\begin{pmatrix} x \\ y \end{pmatrix}= \begin{pmatrix} 25 \\ 64 \end{pmatrix}$$


In [11]:
A = np.array([[1, 1], [2, 4]])
B = np.array([25, 64])

x = np.linalg.solve(A, B)
print(x)

[18.  7.]


In [13]:
np.allclose(A@x, B)

True